name: Update IPTV Links

on:
  schedule:
    - cron: '0 0,12 * * *' # 每天北京时间 8:00 和 20:00 自动运行
  workflow_dispatch: # 支持手动点击运行

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许机器人推送代码

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install requests

      - name: 运行核心检测脚本
        run: python main.py

      - name: 提交并推送到仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 加入 epg.xml 和 epg.xml.gz
          git add live.txt live.m3u epg.xml epg.xml.gz log.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto Update IPTV Sources: $(date +'%Y-%m-%d %H:%M')"
          git push
